/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FlowAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1395951996833561745L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FlowAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"idName\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"variant\",\"type\":\"string\"},{\"name\":\"variantName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FlowAvro> ENCODER =
      new BinaryMessageEncoder<FlowAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FlowAvro> DECODER =
      new BinaryMessageDecoder<FlowAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FlowAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FlowAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FlowAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FlowAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FlowAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FlowAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FlowAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FlowAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence idName;
   private java.lang.CharSequence name;
   private java.lang.CharSequence variant;
   private java.lang.CharSequence variantName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FlowAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param idName The new value for idName
   * @param name The new value for name
   * @param variant The new value for variant
   * @param variantName The new value for variantName
   */
  public FlowAvro(java.lang.CharSequence id, java.lang.CharSequence idName, java.lang.CharSequence name, java.lang.CharSequence variant, java.lang.CharSequence variantName) {
    this.id = id;
    this.idName = idName;
    this.name = name;
    this.variant = variant;
    this.variantName = variantName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return idName;
    case 2: return name;
    case 3: return variant;
    case 4: return variantName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: idName = (java.lang.CharSequence)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: variant = (java.lang.CharSequence)value$; break;
    case 4: variantName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'idName' field.
   * @return The value of the 'idName' field.
   */
  public java.lang.CharSequence getIdName() {
    return idName;
  }


  /**
   * Sets the value of the 'idName' field.
   * @param value the value to set.
   */
  public void setIdName(java.lang.CharSequence value) {
    this.idName = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'variant' field.
   * @return The value of the 'variant' field.
   */
  public java.lang.CharSequence getVariant() {
    return variant;
  }


  /**
   * Sets the value of the 'variant' field.
   * @param value the value to set.
   */
  public void setVariant(java.lang.CharSequence value) {
    this.variant = value;
  }

  /**
   * Gets the value of the 'variantName' field.
   * @return The value of the 'variantName' field.
   */
  public java.lang.CharSequence getVariantName() {
    return variantName;
  }


  /**
   * Sets the value of the 'variantName' field.
   * @param value the value to set.
   */
  public void setVariantName(java.lang.CharSequence value) {
    this.variantName = value;
  }

  /**
   * Creates a new FlowAvro RecordBuilder.
   * @return A new FlowAvro RecordBuilder
   */
  public static FlowAvro.Builder newBuilder() {
    return new FlowAvro.Builder();
  }

  /**
   * Creates a new FlowAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FlowAvro RecordBuilder
   */
  public static FlowAvro.Builder newBuilder(FlowAvro.Builder other) {
    if (other == null) {
      return new FlowAvro.Builder();
    } else {
      return new FlowAvro.Builder(other);
    }
  }

  /**
   * Creates a new FlowAvro RecordBuilder by copying an existing FlowAvro instance.
   * @param other The existing instance to copy.
   * @return A new FlowAvro RecordBuilder
   */
  public static FlowAvro.Builder newBuilder(FlowAvro other) {
    if (other == null) {
      return new FlowAvro.Builder();
    } else {
      return new FlowAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for FlowAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FlowAvro>
    implements org.apache.avro.data.RecordBuilder<FlowAvro> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence idName;
    private java.lang.CharSequence name;
    private java.lang.CharSequence variant;
    private java.lang.CharSequence variantName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(FlowAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.idName)) {
        this.idName = data().deepCopy(fields()[1].schema(), other.idName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.variant)) {
        this.variant = data().deepCopy(fields()[3].schema(), other.variant);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.variantName)) {
        this.variantName = data().deepCopy(fields()[4].schema(), other.variantName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing FlowAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(FlowAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idName)) {
        this.idName = data().deepCopy(fields()[1].schema(), other.idName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.variant)) {
        this.variant = data().deepCopy(fields()[3].schema(), other.variant);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.variantName)) {
        this.variantName = data().deepCopy(fields()[4].schema(), other.variantName);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public FlowAvro.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public FlowAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'idName' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdName() {
      return idName;
    }


    /**
      * Sets the value of the 'idName' field.
      * @param value The value of 'idName'.
      * @return This builder.
      */
    public FlowAvro.Builder setIdName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.idName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'idName' field has been set.
      * @return True if the 'idName' field has been set, false otherwise.
      */
    public boolean hasIdName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'idName' field.
      * @return This builder.
      */
    public FlowAvro.Builder clearIdName() {
      idName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public FlowAvro.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public FlowAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'variant' field.
      * @return The value.
      */
    public java.lang.CharSequence getVariant() {
      return variant;
    }


    /**
      * Sets the value of the 'variant' field.
      * @param value The value of 'variant'.
      * @return This builder.
      */
    public FlowAvro.Builder setVariant(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.variant = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'variant' field has been set.
      * @return True if the 'variant' field has been set, false otherwise.
      */
    public boolean hasVariant() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'variant' field.
      * @return This builder.
      */
    public FlowAvro.Builder clearVariant() {
      variant = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'variantName' field.
      * @return The value.
      */
    public java.lang.CharSequence getVariantName() {
      return variantName;
    }


    /**
      * Sets the value of the 'variantName' field.
      * @param value The value of 'variantName'.
      * @return This builder.
      */
    public FlowAvro.Builder setVariantName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.variantName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'variantName' field has been set.
      * @return True if the 'variantName' field has been set, false otherwise.
      */
    public boolean hasVariantName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'variantName' field.
      * @return This builder.
      */
    public FlowAvro.Builder clearVariantName() {
      variantName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FlowAvro build() {
      try {
        FlowAvro record = new FlowAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.idName = fieldSetFlags()[1] ? this.idName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.variant = fieldSetFlags()[3] ? this.variant : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.variantName = fieldSetFlags()[4] ? this.variantName : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FlowAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<FlowAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FlowAvro>
    READER$ = (org.apache.avro.io.DatumReader<FlowAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.idName);

    out.writeString(this.name);

    out.writeString(this.variant);

    out.writeString(this.variantName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.idName = in.readString(this.idName instanceof Utf8 ? (Utf8)this.idName : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.variant = in.readString(this.variant instanceof Utf8 ? (Utf8)this.variant : null);

      this.variantName = in.readString(this.variantName instanceof Utf8 ? (Utf8)this.variantName : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.idName = in.readString(this.idName instanceof Utf8 ? (Utf8)this.idName : null);
          break;

        case 2:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 3:
          this.variant = in.readString(this.variant instanceof Utf8 ? (Utf8)this.variant : null);
          break;

        case 4:
          this.variantName = in.readString(this.variantName instanceof Utf8 ? (Utf8)this.variantName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










