/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OperationAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -333434262847117584L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OperationAvro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"service\",\"type\":\"string\"},{\"name\":\"environment\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"durationUs\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OperationAvro> ENCODER =
      new BinaryMessageEncoder<OperationAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OperationAvro> DECODER =
      new BinaryMessageDecoder<OperationAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OperationAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OperationAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OperationAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OperationAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OperationAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OperationAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OperationAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OperationAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence name;
   private java.lang.CharSequence service;
   private java.lang.CharSequence environment;
   private long timestamp;
   private int durationUs;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OperationAvro() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param service The new value for service
   * @param environment The new value for environment
   * @param timestamp The new value for timestamp
   * @param durationUs The new value for durationUs
   */
  public OperationAvro(java.lang.CharSequence name, java.lang.CharSequence service, java.lang.CharSequence environment, java.lang.Long timestamp, java.lang.Integer durationUs) {
    this.name = name;
    this.service = service;
    this.environment = environment;
    this.timestamp = timestamp;
    this.durationUs = durationUs;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return service;
    case 2: return environment;
    case 3: return timestamp;
    case 4: return durationUs;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: service = (java.lang.CharSequence)value$; break;
    case 2: environment = (java.lang.CharSequence)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    case 4: durationUs = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'service' field.
   * @return The value of the 'service' field.
   */
  public java.lang.CharSequence getService() {
    return service;
  }


  /**
   * Sets the value of the 'service' field.
   * @param value the value to set.
   */
  public void setService(java.lang.CharSequence value) {
    this.service = value;
  }

  /**
   * Gets the value of the 'environment' field.
   * @return The value of the 'environment' field.
   */
  public java.lang.CharSequence getEnvironment() {
    return environment;
  }


  /**
   * Sets the value of the 'environment' field.
   * @param value the value to set.
   */
  public void setEnvironment(java.lang.CharSequence value) {
    this.environment = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'durationUs' field.
   * @return The value of the 'durationUs' field.
   */
  public int getDurationUs() {
    return durationUs;
  }


  /**
   * Sets the value of the 'durationUs' field.
   * @param value the value to set.
   */
  public void setDurationUs(int value) {
    this.durationUs = value;
  }

  /**
   * Creates a new OperationAvro RecordBuilder.
   * @return A new OperationAvro RecordBuilder
   */
  public static OperationAvro.Builder newBuilder() {
    return new OperationAvro.Builder();
  }

  /**
   * Creates a new OperationAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OperationAvro RecordBuilder
   */
  public static OperationAvro.Builder newBuilder(OperationAvro.Builder other) {
    if (other == null) {
      return new OperationAvro.Builder();
    } else {
      return new OperationAvro.Builder(other);
    }
  }

  /**
   * Creates a new OperationAvro RecordBuilder by copying an existing OperationAvro instance.
   * @param other The existing instance to copy.
   * @return A new OperationAvro RecordBuilder
   */
  public static OperationAvro.Builder newBuilder(OperationAvro other) {
    if (other == null) {
      return new OperationAvro.Builder();
    } else {
      return new OperationAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for OperationAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OperationAvro>
    implements org.apache.avro.data.RecordBuilder<OperationAvro> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence service;
    private java.lang.CharSequence environment;
    private long timestamp;
    private int durationUs;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(OperationAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.service)) {
        this.service = data().deepCopy(fields()[1].schema(), other.service);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.environment)) {
        this.environment = data().deepCopy(fields()[2].schema(), other.environment);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.durationUs)) {
        this.durationUs = data().deepCopy(fields()[4].schema(), other.durationUs);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OperationAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(OperationAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.service)) {
        this.service = data().deepCopy(fields()[1].schema(), other.service);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.environment)) {
        this.environment = data().deepCopy(fields()[2].schema(), other.environment);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.durationUs)) {
        this.durationUs = data().deepCopy(fields()[4].schema(), other.durationUs);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public OperationAvro.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public OperationAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'service' field.
      * @return The value.
      */
    public java.lang.CharSequence getService() {
      return service;
    }


    /**
      * Sets the value of the 'service' field.
      * @param value The value of 'service'.
      * @return This builder.
      */
    public OperationAvro.Builder setService(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.service = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'service' field has been set.
      * @return True if the 'service' field has been set, false otherwise.
      */
    public boolean hasService() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'service' field.
      * @return This builder.
      */
    public OperationAvro.Builder clearService() {
      service = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'environment' field.
      * @return The value.
      */
    public java.lang.CharSequence getEnvironment() {
      return environment;
    }


    /**
      * Sets the value of the 'environment' field.
      * @param value The value of 'environment'.
      * @return This builder.
      */
    public OperationAvro.Builder setEnvironment(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.environment = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'environment' field has been set.
      * @return True if the 'environment' field has been set, false otherwise.
      */
    public boolean hasEnvironment() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'environment' field.
      * @return This builder.
      */
    public OperationAvro.Builder clearEnvironment() {
      environment = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public OperationAvro.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public OperationAvro.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'durationUs' field.
      * @return The value.
      */
    public int getDurationUs() {
      return durationUs;
    }


    /**
      * Sets the value of the 'durationUs' field.
      * @param value The value of 'durationUs'.
      * @return This builder.
      */
    public OperationAvro.Builder setDurationUs(int value) {
      validate(fields()[4], value);
      this.durationUs = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'durationUs' field has been set.
      * @return True if the 'durationUs' field has been set, false otherwise.
      */
    public boolean hasDurationUs() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'durationUs' field.
      * @return This builder.
      */
    public OperationAvro.Builder clearDurationUs() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OperationAvro build() {
      try {
        OperationAvro record = new OperationAvro();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.service = fieldSetFlags()[1] ? this.service : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.environment = fieldSetFlags()[2] ? this.environment : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.durationUs = fieldSetFlags()[4] ? this.durationUs : (java.lang.Integer) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OperationAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<OperationAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OperationAvro>
    READER$ = (org.apache.avro.io.DatumReader<OperationAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeString(this.service);

    out.writeString(this.environment);

    out.writeLong(this.timestamp);

    out.writeInt(this.durationUs);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.service = in.readString(this.service instanceof Utf8 ? (Utf8)this.service : null);

      this.environment = in.readString(this.environment instanceof Utf8 ? (Utf8)this.environment : null);

      this.timestamp = in.readLong();

      this.durationUs = in.readInt();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.service = in.readString(this.service instanceof Utf8 ? (Utf8)this.service : null);
          break;

        case 2:
          this.environment = in.readString(this.environment instanceof Utf8 ? (Utf8)this.environment : null);
          break;

        case 3:
          this.timestamp = in.readLong();
          break;

        case 4:
          this.durationUs = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










