/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2280898664400742533L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"idName\",\"type\":\"string\"},{\"name\":\"companyId\",\"type\":\"string\"},{\"name\":\"companyIdName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserAvro> ENCODER =
      new BinaryMessageEncoder<UserAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserAvro> DECODER =
      new BinaryMessageDecoder<UserAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence idName;
   private java.lang.CharSequence companyId;
   private java.lang.CharSequence companyIdName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param idName The new value for idName
   * @param companyId The new value for companyId
   * @param companyIdName The new value for companyIdName
   */
  public UserAvro(java.lang.CharSequence id, java.lang.CharSequence idName, java.lang.CharSequence companyId, java.lang.CharSequence companyIdName) {
    this.id = id;
    this.idName = idName;
    this.companyId = companyId;
    this.companyIdName = companyIdName;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return idName;
    case 2: return companyId;
    case 3: return companyIdName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: idName = (java.lang.CharSequence)value$; break;
    case 2: companyId = (java.lang.CharSequence)value$; break;
    case 3: companyIdName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'idName' field.
   * @return The value of the 'idName' field.
   */
  public java.lang.CharSequence getIdName() {
    return idName;
  }


  /**
   * Sets the value of the 'idName' field.
   * @param value the value to set.
   */
  public void setIdName(java.lang.CharSequence value) {
    this.idName = value;
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public java.lang.CharSequence getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.CharSequence value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'companyIdName' field.
   * @return The value of the 'companyIdName' field.
   */
  public java.lang.CharSequence getCompanyIdName() {
    return companyIdName;
  }


  /**
   * Sets the value of the 'companyIdName' field.
   * @param value the value to set.
   */
  public void setCompanyIdName(java.lang.CharSequence value) {
    this.companyIdName = value;
  }

  /**
   * Creates a new UserAvro RecordBuilder.
   * @return A new UserAvro RecordBuilder
   */
  public static UserAvro.Builder newBuilder() {
    return new UserAvro.Builder();
  }

  /**
   * Creates a new UserAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserAvro RecordBuilder
   */
  public static UserAvro.Builder newBuilder(UserAvro.Builder other) {
    if (other == null) {
      return new UserAvro.Builder();
    } else {
      return new UserAvro.Builder(other);
    }
  }

  /**
   * Creates a new UserAvro RecordBuilder by copying an existing UserAvro instance.
   * @param other The existing instance to copy.
   * @return A new UserAvro RecordBuilder
   */
  public static UserAvro.Builder newBuilder(UserAvro other) {
    if (other == null) {
      return new UserAvro.Builder();
    } else {
      return new UserAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserAvro>
    implements org.apache.avro.data.RecordBuilder<UserAvro> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence idName;
    private java.lang.CharSequence companyId;
    private java.lang.CharSequence companyIdName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(UserAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.idName)) {
        this.idName = data().deepCopy(fields()[1].schema(), other.idName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.companyId)) {
        this.companyId = data().deepCopy(fields()[2].schema(), other.companyId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.companyIdName)) {
        this.companyIdName = data().deepCopy(fields()[3].schema(), other.companyIdName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing UserAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(UserAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.idName)) {
        this.idName = data().deepCopy(fields()[1].schema(), other.idName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.companyId)) {
        this.companyId = data().deepCopy(fields()[2].schema(), other.companyId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.companyIdName)) {
        this.companyIdName = data().deepCopy(fields()[3].schema(), other.companyIdName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public UserAvro.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public UserAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'idName' field.
      * @return The value.
      */
    public java.lang.CharSequence getIdName() {
      return idName;
    }


    /**
      * Sets the value of the 'idName' field.
      * @param value The value of 'idName'.
      * @return This builder.
      */
    public UserAvro.Builder setIdName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.idName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'idName' field has been set.
      * @return True if the 'idName' field has been set, false otherwise.
      */
    public boolean hasIdName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'idName' field.
      * @return This builder.
      */
    public UserAvro.Builder clearIdName() {
      idName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public UserAvro.Builder setCompanyId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.companyId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public UserAvro.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyIdName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyIdName() {
      return companyIdName;
    }


    /**
      * Sets the value of the 'companyIdName' field.
      * @param value The value of 'companyIdName'.
      * @return This builder.
      */
    public UserAvro.Builder setCompanyIdName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.companyIdName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'companyIdName' field has been set.
      * @return True if the 'companyIdName' field has been set, false otherwise.
      */
    public boolean hasCompanyIdName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'companyIdName' field.
      * @return This builder.
      */
    public UserAvro.Builder clearCompanyIdName() {
      companyIdName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserAvro build() {
      try {
        UserAvro record = new UserAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.idName = fieldSetFlags()[1] ? this.idName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.companyId = fieldSetFlags()[2] ? this.companyId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.companyIdName = fieldSetFlags()[3] ? this.companyIdName : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserAvro>
    READER$ = (org.apache.avro.io.DatumReader<UserAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.idName);

    out.writeString(this.companyId);

    out.writeString(this.companyIdName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.idName = in.readString(this.idName instanceof Utf8 ? (Utf8)this.idName : null);

      this.companyId = in.readString(this.companyId instanceof Utf8 ? (Utf8)this.companyId : null);

      this.companyIdName = in.readString(this.companyIdName instanceof Utf8 ? (Utf8)this.companyIdName : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.idName = in.readString(this.idName instanceof Utf8 ? (Utf8)this.idName : null);
          break;

        case 2:
          this.companyId = in.readString(this.companyId instanceof Utf8 ? (Utf8)this.companyId : null);
          break;

        case 3:
          this.companyIdName = in.readString(this.companyIdName instanceof Utf8 ? (Utf8)this.companyIdName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










